/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {Persona} from '../models/persona';

export interface DoctorRes {
  especialidadId?: number;
  honorarios?: number;
  id?: number;
  licencia?: string;
  persona?: Persona;
}
