/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EspecialidadReq } from '../models/especialidad-req';
import { Persona } from '../models/persona';
export interface DoctorRes {
  especialidad?: EspecialidadReq;
  honorarios?: number;
  id?: number;
  licencia?: string;
  persona?: Persona;
}
