/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {Persona} from '../models/persona';
import {EspecialidadReq} from "./especialidad-req";

export interface DoctorRes {
  especialidad?: EspecialidadReq;
  honorarios?: number;
  id?: number;
  licencia?: string;
  persona?: Persona;
}
