/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {Especialidad} from './especialidad';
import {Paciente} from './paciente';
import {Persona} from './persona';

export interface Doctor {
  especialidad?: Especialidad;
  honorarios?: number;
  id?: number;
  licencia?: string;
  pacientes?: Array<Paciente>;
  persona?: Persona;
}
