/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {PersonaReq} from '../models/persona-req';

export interface DoctorReq {
  especialidadId: number;
  honorarios: number;
  licencia: string;
  persona?: PersonaReq;
}
