/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Especialidad {
  descripcion?: string;
  fotoUrl?: string;
  id?: number;
  nombre?: string;
}
