/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {RegistroMedico} from '../models/registro-medico';

export interface HistoriaClinicaRes {
  id?: number;
  registroMedicos?: Array<RegistroMedico>;
}
