/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RegistroMedicoRes } from '../models/registro-medico-res';
export interface HistoriaClinicaRes {
  id?: number;
  registroMedicos?: Array<RegistroMedicoRes>;
}
