/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PersonaReq } from '../models/persona-req';
export interface PacienteReq {
  persona?: PersonaReq;
}
