/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HistoriaClinica} from '../models/historia-clinica';
import {Persona} from '../models/persona';

export interface Paciente {
  historiaClinica?: HistoriaClinica;
  id?: number;
  persona?: Persona;
}
