/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {Persona} from '../models/persona';

export interface PacienteRes {
  id?: number;
  persona?: Persona;
}
