/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PersonaReq {
  dni: string;
  edad: number;
  email: string;
  nombre: string;
  telefono: string;
}
