/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Persona {
  dni?: string;
  edad?: number;
  email?: string;
  id?: number;
  nombre?: string;
  telefono?: string;
}
