/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DoctorRes } from '../models/doctor-res';
export interface RegistroMedicoRes {
  diagnostico?: string;
  doctor?: DoctorRes;
  fecha?: string;
  id?: number;
  motivoDeLaConsulta?: string;
  observaciones?: string;
  seguimiento?: string;
  sintomas?: Array<string>;
  tratamiento?: string;
}
