/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistroMedicoReq {
  diagnostico: string;
  doctorId: number;
  fecha: string;
  motivoDeLaConsulta: string;
  observaciones: string;
  seguimiento: string;
  sintomas: Array<string>;
  tratamiento: string;
}
