/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DoctorRes } from '../models/doctor-res';
import { PacienteRes } from '../models/paciente-res';
export interface TurnoRes {
  doctor?: DoctorRes;
  estadoTurno?: 'PENDIENTE' | 'CANCELADO' | 'COMPLETADO';
  fechaHora?: string;
  id?: number;
  paciente?: PacienteRes;
}
