/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Usuario {
  email?: string;
  entidadId?: number;
  id?: number;
  rol?: 'DOCTOR' | 'PACIENTE';
}
