/**
 * Telemedicina API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {RegistroMedicoRes} from './registroMedicoRes';


export interface HistoriaClinicaRes {
    id?: number;
    registroMedicos?: Array<RegistroMedicoRes>;
}

