/**
 * Telemedicina API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonaReq { 
    nombre: string;
    apellido: string;
    fdn: string;
    sexo: PersonaReq.SexoEnum;
    dni: string;
    telefono: string;
    email: string;
    fotoUrl?: string;
}
export namespace PersonaReq {
    export type SexoEnum = 'M' | 'F';
    export const SexoEnum = {
        M: 'M' as SexoEnum,
        F: 'F' as SexoEnum
    };
}


