/**
 * Telemedicina API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Persona { 
    id?: number;
    nombre?: string;
    apellido?: string;
    fdn?: string;
    sexo?: Persona.SexoEnum;
    dni?: string;
    telefono?: string;
    email?: string;
    fotoUrl?: string;
}
export namespace Persona {
    export type SexoEnum = 'M' | 'F';
    export const SexoEnum = {
        M: 'M' as SexoEnum,
        F: 'F' as SexoEnum
    };
}


