/**
 * Telemedicina API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Persona { 
    id?: number;
    nombre?: string;
    edad?: number;
    dni?: string;
    telefono?: string;
    email?: string;
    fotoUrl?: string;
}

