/**
 * Telemedicina API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegistroMedicoReq { 
    fecha: string;
    doctorId: number;
    motivoDeLaConsulta: string;
    sintomas: Array<string>;
    diagnostico: string;
    tratamiento: string;
    seguimiento: string;
    observaciones: string;
}

