/**
 * Telemedicina API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Usuario { 
    id?: number;
    rol?: Usuario.RolEnum;
    email?: string;
    entidadId?: number;
}
export namespace Usuario {
    export type RolEnum = 'DOCTOR' | 'PACIENTE';
    export const RolEnum = {
        Doctor: 'DOCTOR' as RolEnum,
        Paciente: 'PACIENTE' as RolEnum
    };
}


