export * from './doctorController.service';
import { DoctorControllerService } from './doctorController.service';
export * from './especialidadController.service';
import { EspecialidadControllerService } from './especialidadController.service';
export * from './historiaClinicaController.service';
import { HistoriaClinicaControllerService } from './historiaClinicaController.service';
export * from './pacienteController.service';
import { PacienteControllerService } from './pacienteController.service';
export * from './registroMedicoController.service';
import { RegistroMedicoControllerService } from './registroMedicoController.service';
export * from './turnoController.service';
import { TurnoControllerService } from './turnoController.service';
export * from './usuarioController.service';
import { UsuarioControllerService } from './usuarioController.service';
export const APIS = [DoctorControllerService, EspecialidadControllerService, HistoriaClinicaControllerService, PacienteControllerService, RegistroMedicoControllerService, TurnoControllerService, UsuarioControllerService];
