spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update


springdoc:
  default-produces-media-type: application/json


backend:
  url: ${BACKEND_URL}

server:
  port: 8080