spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update


  flyway:
    defaultSchema: public
    user: ${DB_USER}
    password: ${DB_PASSWORD}

springdoc:
  default-produces-media-type: application/json

  ic:

backend:
  url: ${BACKEND_URL}

server:
  port: 8080