spring:
  application:
    name: TelemedicinaApp
  server:
    port: 8080
  datasource:
      url: jdbc:mysql://localhost:3306/telemedicina?useSSL=false&serverTimeZone=UTC
      username: root
      password: root
  jpa:
      hibernate:
          ddl-auto: update
          show-sql: true
    
  
  
 
springdoc:
  swagger-ui:
    path: /doc/swagger-ui.html