spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none


springdoc:
  default-produces-media-type: application/json


backend:
  url: ${BACKEND_URL}

server:
  port: 8080