spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    gcp:
      core:
        enabled: false
      sql:
        enabled: false

server:
  port: 8080