/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Doctor } from './models/doctor';
export type { DoctorReq } from './models/doctor-req';
export type { DoctorRes } from './models/doctor-res';
export type { Especialidad } from './models/especialidad';
export type { EspecialidadReq } from './models/especialidad-req';
export type { HistoriaClinica } from './models/historia-clinica';
export type { HistoriaClinicaRes } from './models/historia-clinica-res';
export type { Paciente } from './models/paciente';
export type { PacienteReq } from './models/paciente-req';
export type { PacienteRes } from './models/paciente-res';
export type { Persona } from './models/persona';
export type { PersonaReq } from './models/persona-req';
export type { RegistroMedico } from './models/registro-medico';
export type { RegistroMedicoReq } from './models/registro-medico-req';
export type { RegistroMedicoRes } from './models/registro-medico-res';
export type { TurnoReq } from './models/turno-req';
export type { TurnoRes } from './models/turno-res';
export type { Usuario } from './models/usuario';
