/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { TurnoControllerService } from './services/turno-controller.service';
export { RegistroMedicoControllerService } from './services/registro-medico-controller.service';
export { PacienteControllerService } from './services/paciente-controller.service';
export { EspecialidadControllerService } from './services/especialidad-controller.service';
export { DoctorControllerService } from './services/doctor-controller.service';
export { UsuarioControllerService } from './services/usuario-controller.service';
export { HistoriaClinicaControllerService } from './services/historia-clinica-controller.service';
