name: renew expired database
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  renew-db:
    name: renew expired database
    runs-on: ubuntu-latest
    steps:
      - name: holis
        run: echo hello
